<?php
/**
 * FlowCommerce
 *
 * FlowCommerce_FlowConnector
 * @category    FlowCommerce
 * @package     FlowCommerce_FlowConnector
 * @author      FlowCommerce
 * @copyright   Copyright (c) 2019 FlowCommerce
 */

/** @var $block \FlowCommerce\FlowConnector\Block\FlowJS */
?>
<?php if ($block->isFlowEnabled()) : ?>
    <?php
    $maxCatalogHideMs = (int)$block->getFlowMaxCatalogHideMs();
    $maxCartHideMs = (int)$block->getFlowMaxCartHideMs();
    ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "flowInit": {
                "organization_id": "<?= /* @escapeNotVerified */ (string)$block->getFlowOrganizationId() ?>",
                "enabled": true,
                "production": <?= /* @escapeNotVerified */ (int)$block->isFlowProduction() ?>,
                "support_discounts": <?= /* @escapeNotVerified */ (int)$block->isFlowSupportMagentoDiscounts() ?>,
                "cart_localize": <?= /* @escapeNotVerified */ (int)$block->isFlowCartLocalize() ?>,
                "catalog_localize": <?= /* @escapeNotVerified */ (int)$block->isFlowCatalogLocalize() ?>,
                "pricing_timeout": <?= /* @escapeNotVerified */ $maxCatalogHideMs ?>,
                "cart_timeout": <?= /* @escapeNotVerified */ $maxCartHideMs ?>,
                "payment_methods_enabled": <?= /* @escapeNotVerified */ (int)$block->isPaymentMethodsPDPEnabled() ?>,
                "shipping_window_enabled": <?= /* @escapeNotVerified */ (int)$block->isShippingWindowPDPEnabled() ?>,
                "tax_duty_enabled": <?= /* @escapeNotVerified */ (int)$block->isTaxDutyMessagingEnabled() ?>,
                "country_picker_enabled": <?= /* @escapeNotVerified */ (int)$block->isCountryPickerEnabled() ?>,
                "base_currency_code": "<?= /* @escapeNotVerified */ (string)$block->getBaseCurrencyCode() ?>"
            }
        }
    }
    </script>

    <script type="text/javascript">
    setTimeout(function(){
        document.head.append(`
            body [data-role="priceBox"] span.price {
                opacity: 1;
            }
        `);
    }, <?= $maxCatalogHideMs ?>);

    setTimeout(function(){
        document.head.append(`
            body.checkout-cart-index .form-cart span.price,
            body.checkout-cart-index .cart-summary span.price,
            body #minicart-content-wrapper span.price {
                opacity: 1;
            }
        `);
    }, <?= $maxCartHideMs ?>);
    </script>
    <?php if ($maxCatalogHideMs > 0) : ?>
        <style>
        [data-role="priceBox"] span.price {
            opacity: 0;
        }
        body.flow-catalog-localized [data-role="priceBox"] span.price {
            opacity: 1;
        }
        </style>
    <?php endif; ?>
    <?php if ($maxCartHideMs > 0) : ?>
        <style>
        .checkout-cart-index .form-cart span.price,
        .checkout-cart-index .cart-summary span.price,
        #minicart-content-wrapper span.price {
            opacity: 0;
        }
        .flow-cart-localized.checkout-cart-index .form-cart span.price,
        .flow-cart-totals-localized.checkout-cart-index .cart-summary span.price,
        .flow-cart-localized #minicart-content-wrapper span.price {
            opacity: 1;
        }
        </style>
    <?php endif; ?>
<?php else: ?>
    <script type="text/javascript">
        if('require' in window) {
            require.config({
                config: {
                    mixins: {
                        'Magento_ConfigurableProduct/js/configurable': {
                            'FlowCommerce_FlowConnector/js/configurable-mixin': false
                        },
                        'Magento_Catalog/js/price-box': {
                            'FlowCommerce_FlowConnector/js/price-box-mixin': false
                        },
                        'Magento_Swatches/js/swatch-renderer': {
                            'FlowCommerce_FlowConnector/js/swatch-renderer-mixin': false
                        },
                        'Magento_Checkout/js/shopping-cart': {
                            'FlowCommerce_FlowConnector/js/shopping-cart-mixin': false
                        }
                    }
                }
            });
        }
    </script>
<?php endif; ?>
