<?php
/**
 * FlowCommerce
 *
 * FlowCommerce_FlowConnector
 * @category    FlowCommerce
 * @package     FlowCommerce_FlowConnector
 * @author      FlowCommerce
 * @copyright   Copyright (c) 2020 FlowCommerce
 */

/** @var $block \FlowCommerce\FlowConnector\Block\FlowProductInfo */
?>
<span class="flow-accepted-payment-methods" id="flow-accepted-payment-methods"></span>
<span class="flow-shipping-window" id="flow-shipping-window" flow-shipping-window></span>
