<?php
/**
 * FlowCommerce
 *
 * FlowCommerce_FlowConnector
 * @category    FlowCommerce
 * @package     FlowCommerce_FlowConnector
 * @author      FlowCommerce
 * @copyright   Copyright (c) 2019 FlowCommerce
 */

/** @var $block \FlowCommerce\FlowConnector\Block\FlowJS */
?>
<?php if ($block->isFlowJsEnabled()) : ?>
    <script type="text/javascript">
    window.flow_enabled = true;
    window.flow_organization_id = "<?= $block->getFlowOrganizationId(); ?>";
    window.flow_production = "<?= (int)$block->isFlowProduction(); ?>";
    window.flow_flowjs_url = "<?= $block->getFlowJsUrl(); ?>";
    window.flow_support_magento_discounts = "<?= (int)$block->isFlowSupportMagentoDiscounts(); ?>";
    window.flow_cart_localize = <?= (int)$block->isFlowCartLocalize(); ?>;
    window.flow_catalog_localize = <?= (int)$block->isFlowCatalogLocalize(); ?>;
    window.flow_pricing_timeout = "<?= (int)$block->getFlowMaxCatalogHideMs(); ?>";
    window.flow_cart_timeout = "<?= (int)$block->getFlowMaxCartHideMs(); ?>";
    !function (f, l, o, w, i, n, g) {
        f[i] = f[i] || {};f[i].cmd = f[i].cmd || function () {
            (f[i].q = f[i].q || []).push(arguments);};n = l.createElement(o);
        n.src = w;g = l.getElementsByTagName(o)[0];g.parentNode.insertBefore(n, g);
    }(window,document,'script',window.flow_flowjs_url,'flow');
    setTimeout(function(){
        document.head.append(`
            body [data-role="priceBox"] span.price {
                opacity: 1;
            } 
        `);
    }, window.flow_pricing_timeout);
    setTimeout(function(){
        document.head.append(`
            body.checkout-cart-index .form-cart span.price,
            body.checkout-cart-index .cart-summary span.price,
            body #minicart-content-wrapper span.price {
                opacity: 1;
            }
        `);
    }, window.flow_cart_timeout);
    </script>
    <?php if ($block->getFlowMaxCatalogHideMs() > 0) : ?>
        <style>
        [data-role="priceBox"] span.price {
            opacity: 0;
        } 
        body.flow-catalog-localized [data-role="priceBox"] span.price {
            opacity: 1;
        }
        </style>
    <?php endif; ?>
    <?php if ((int)$block->getFlowMaxCartHideMs() > 0) : ?>
        <style>
        .checkout-cart-index .form-cart span.price,
        .checkout-cart-index .cart-summary span.price,
        #minicart-content-wrapper span.price {
            opacity: 0;
        } 
        .flow-cart-localized.checkout-cart-index .form-cart span.price,
        .flow-cart-totals-localized.checkout-cart-index .cart-summary span.price,
        .flow-cart-localized #minicart-content-wrapper span.price {
            opacity: 1;
        }
        </style>
    <?php endif; ?>
<?php endif; ?>
