<?php
/**
 * FlowCommerce
 *
 * FlowCommerce_FlowConnector
 * @category    FlowCommerce
 * @package     FlowCommerce_FlowConnector
 * @author      FlowCommerce
 * @copyright   Copyright (c) 2019 FlowCommerce
 */

/** @var $block \FlowCommerce\FlowConnector\Block\FlowCountryPicker */
?>
<script type="text/javascript">
window.flow_country_picker_enabled = <?php echo $block->isCountryPickerEnabled(); ?>
</script>
