<?php
/**
 * FlowCommerce
 *
 * FlowCommerce_FlowConnector
 * @category    FlowCommerce
 * @package     FlowCommerce_FlowConnector
 * @author      FlowCommerce
 * @copyright   Copyright (c) 2019 FlowCommerce
 */

/** @var $block \FlowCommerce\FlowConnector\Block\FlowCountryPicker */
?>
<?php if ($block->isCountryPickerEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "FlowCommerce_FlowConnector/js/flow-country-picker": {}
            }
        }
    </script>
<?php endif; ?>
