FROM bitnami/magento:2.2.6-debian-9-r8

ADD . /opt/flowcommerce/flowconnector

WORKDIR /opt/bitnami/magento/htdocs

RUN find . -type d -print0 | xargs -0 chmod 775 && \
  find . -type f -print0 | xargs -0 chmod 664 && \
  chown -R bitnami:daemon /opt/bitnami/magento/htdocs && \
  composer config repositories.flowconnector path /opt/flowcommerce/flowconnector && \
  composer config repo.0 false && \
  composer require --no-interaction flowcommerce/flowconnector @dev && \
  echo 'memory_limit = 2048M' >> /opt/bitnami/php/lib/php.ini && \
  php bin/magento module:enable --all && \
  php bin/magento setup:di:compile

EXPOSE 80 443

ENTRYPOINT ["/opt/flowcommerce/flowconnector/entrypoint.sh"]
CMD [ "httpd", "-f", "/bitnami/apache/conf/httpd.conf", "-DFOREGROUND" ]