FROM bitnami/magento:2.3.2

ADD . /opt/flowcommerce/flowconnector

WORKDIR /opt/bitnami/magento/htdocs

ARG MAGENTO2_REPO_PRIVATE_KEY

RUN find . -type d -print0 | xargs -0 chmod 775 && \
    find . -type f -print0 | xargs -0 chmod 664 && \
    chown -R bitnami:daemon . && \
    echo 'memory_limit = -1' >> /opt/bitnami/php/lib/php.ini

RUN composer config repositories.flowconnector '{ "type": "path", "url": "/opt/flowcommerce/flowconnector", "options" : { "symlink": false } }' && \
    composer config repo.0 false && \
    composer config repositories.magento '{ "type": "composer", "url": "https://repo.magento.com" }' && \
    composer config http-basic.repo.magento.com e09972697200676346ab7a6981ac63fa $MAGENTO2_REPO_PRIVATE_KEY

RUN composer require --no-interaction flowcommerce/flowconnector *@dev \
    magento/module-bundle-sample-data:* \
    magento/module-sales-sample-data:* \
    magento/module-customer-sample-data:* \
    magento/module-catalog-sample-data:* \
    magento/module-theme-sample-data:* \
    magento/module-cms-sample-data:* \
    magento/module-widget-sample-data:* \
    magento/module-catalog-rule-sample-data:* \
    magento/module-sales-rule-sample-data:* \
    magento/module-review-sample-data:* \
    magento/module-tax-sample-data:* \
    magento/module-downloadable-sample-data:* \
    magento/module-msrp-sample-data:* \
    magento/module-wishlist-sample-data:* \
    magento/module-configurable-sample-data:* \
    magento/module-product-links-sample-data:* \
    magento/module-grouped-product-sample-data:* \
    magento/module-offline-shipping-sample-data:* \
    magento/module-swatches-sample-data:* \
    magento/sample-data-media:*

RUN php bin/magento module:enable --all
RUN php bin/magento setup:di:compile

RUN find . -type d -print0 | xargs -0 chmod 775 && \
    find . -type f -print0 | xargs -0 chmod 664 && \
    chown -R bitnami:daemon .

EXPOSE 80 443

ENTRYPOINT ["/opt/flowcommerce/flowconnector/entrypoint.sh"]
CMD [ "/run.sh" ]
