version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami'
    networks:
      - backend
  magento:
    image: '479720515435.dkr.ecr.us-east-1.amazonaws.com/magento-flow-connector:k8s-pr-dd0de5c4a46a5626640f076c33bd2055c75fb5bc'
    labels:
      kompose.service.type: nodeport
    environment:
      - NAMI_DEBUG=1
      - NAMI_LOG_LEVEL=trace8
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - COMPOSER_MEMORY_LIMIT=-1
    ports:
      - '8080:80'
    volumes:
      - '/bitnami'
    depends_on:
      - mariadb
    links:
      - mariadb
    networks:
      - backend
volumes:
  mariadb_data:
    driver: local
networks:
  backend:
    driver: bridge