{{- $fullName := include "deploy.fullname" . -}}
{{- $dbHost := include "magento.mariadb.fullname" . -}}
{{- range $stage, $deployment := index .Values "deployments" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-{{ $stage }}
  labels:
    helm.sh/chart: {{ include "deploy.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "deploy.name" $ }}
    app.kubernetes.io/stage: {{ $stage }}
spec:
  replicas: {{ $deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deploy.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/stage: {{ $stage }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "deploy.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/stage: {{ $stage }}
      annotations:
        iam.amazonaws.com/role: {{ $.Values.iamRole }}
    spec:
      imagePullSecrets:
        - name: docker-hub-flowcommerce
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
          - "status.localhost"
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}:{{ $deployment.version }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: MARIADB_HOST
              value: {{ $dbHost }}
            - name: MARIADB_PORT_NUMBER
              value: "3306"
            - name: MAGENTO_DATABASE_NAME
              value: {{ $.Values.magento.db.name | quote }}
            - name: MAGENTO_DATABASE_USER
              value: {{ $.Values.magento.db.user | quote }}
            - name: MAGENTO_DATABASE_PASSWORD
              value: {{ $.Values.magento.db.pass | quote }}
            - name: MAGENTO_USERNAME
              value: {{ $.Values.magento.username | quote }}
            - name: MAGENTO_PASSWORD
              value: {{ $.Values.magento.pass | quote }}
            - name: MAGENTO_EMAIL
              value: {{ $.Values.magento.email | quote }}
            - name: MAGENTO_ADMINURI
              value: {{ $.Values.magento.adminUri | quote }}
            - name: MAGENTO_FIRSTNAME
              value: {{ $.Values.magento.firstName | quote }}
            - name: MAGENTO_LASTNAME
              value: {{ $.Values.magento.lastName | quote }}
            - name: MAGENTO_MODE
              value: {{ $.Values.magento.mode | quote }}
            - name: BASH_DEBUG
              value: "1"
            - name: NAMI_DEBUG
              value: "1"
            - name: NAMI_LOG_LEVEL
              value: "trace8"
{{ toYaml $deployment.env | indent 12 }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /index.php
              port: http
              httpHeaders:
              - name: Host
                value: {{ $deployment.host | quote }}
            initialDelaySeconds: 1000
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /index.php
              port: http
              httpHeaders:
              - name: Host
                value: {{ $deployment.host | quote }}
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
{{ toYaml $.Values.resources | indent 12 }}
          volumeMounts:
            - name: magento-data
              mountPath: /bitnami/magento
            - name: apache-data
              mountPath: /bitnami/apache
      volumes:
        - name: magento-data
          emptyDir: {}
        - name: apache-data
          emptyDir: {}
    {{- with $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $.Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}
